// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wsjodckwcudrshnvnvbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indzam9kY2t3Y3VkcnNobnZudmJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MzIzNjQsImV4cCI6MjA2OTAwODM2NH0.hIFSiYvoAHdavavpo-RXoANJzyexUXjnjUCoKd9pvhQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});